# Generated by Django 2.2.10 on 2020-04-26 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, max_length=254, null=True, upload_to='profile_pictures'),
        ),
    ]
